### ISSUE TITLE
Funktionen-R-Skript 1

### ISSUE THREAD

**Issue by lshrnd** [lshrnd/wissArbeiten_gruppe12#2]
Ich dachte vielleicht sammeln wir mal Ideen für die Funktionen, hier sind meine Überlegungen:

(a) hier würde ich einfach erstmal arithmetisches Mittel, Median, Standardabweichung vorschlagen.
(b) auf jeden Fall den häufigsten Wert und vielleicht auch den am seltensten, mehr fällt mir da erstmal nicht ein
(c) die einzigen zwei kategorialen Merkmale sind ja Studienfach und Mathe-LK, also könnte man anhand des Mathe-LKs aufteilen, wie oft welcher Studiengang studiert wird
(d) auch hier wieder, die Merkmale um die es hier geht sind ausschließlich Alter und Mathe-LK, also könnte man das Durchschnittsalter je nach dem ob Mathe-LK gewählt wurde darstellen, aber hier gibt es bestimmt auch bessere Ideen
(e) die Funktion eignet sich gut für die Interessens-Merkmale, also würde ich da 1 und 2 mit "niedrig", 3, 4 und 5 mit "mittel" und 6 und 7 mit "hoch" kategorisieren.
(f) da es um kategoriale Merkmale geht, würde ich Balkendiagramme vorschlagen

Ich bitte um Feedback und weitere Ideen

**Comment by wilson102099** [comment]
Ein paar Vorschläge von mir:

(a) Modus können wir auch hinzufügen.
(d) Wir können auch die Anzahl der Studenten, die Mathe-LK hatten zwischen bestimmten Alter berechnen. Also z.B. 20 Studenten zwischen 21-26 Alt hatten früher Mathe-LK.
(e) Ich würde vorschlagen dass 1 und 2 mit "niedrig", 3 und 4 mit "mittel", 5 und 6 mit "hoch" , 7 mit "sehr hoch"

**Comment by JKuehne-TU** [comment]
Ein wenig Feedback und ergänzende Vorschläge/Ideen:

Zu (a): Finde ich gut - habe keine weiteren Vorschläge.
Zu (b): Man könnte auch einfach zusätzlich relative Häufigkeiten berechnen.
Zu (c): Durch die Kategorisierung in (e) kann man auch noch die Interessensvariablen auswerten.
Zu (d): Man könnte auch für jedes Alter 20, 21, ... berechnen wie hoch der relative Anteil derjenigen ist, die einen Mathe-LK hatten (unter der Annahme, dass Leute die etwa gleich alt sind zur gleichen Zeit Abitur gemacht haben ist das eventuell interpretierbar).
Zu (e): Mein Vorschlag für die Kategorisierung: Sehr Gering 1; Gering 2,3; Mittel 4; Hoch 5,6; Sehr Hoch 7.
Außerdem könnte man auch verschiedene der Kategorisierungen vornehmen um diese eventuell miteinander vergleichen zu können.
Zu (f): Verständnisfrage: Sollen die Visualisierungen die Variablen nur einzeln darstellen, oder sollen wir auch Zusammenhänge betrachten? (Z.B. könnte man ja auch die Interessen anhand der Studienfächer aufteilen. Oder würde das in eine zusätzliche Funktion gehören?)

**Comment by lshrnd** [comment]
Ich denke mal bei (f) stimmt schon dass man die Zusammenhänge betrachten könnte, ist auf jeden Fall interessanter, aber auch schwieriger mMn. Kannst ja mal probieren ob und wie du das umgesetzt kriegst

**Comment by JKuehne-TU** [comment]
Also weitestgehend sind die Funktionen jetzt fertiggestellt im Branch "Funktionen und Testskripte".
Sowohl das Funktionen-R-Skript 1.R und das Funktionen-R-Skript 2.R.
Nur bei der Funktion (e) habe ich noch ein paar Unsicherheiten.
Ich würde den Branch einfach mit main mergen und falls es keine weiteren Änderungsvorschläge gibt könnte man mit der Auswertung beginnen.

**Comment by amiiir94** [comment]
(c) Alle Variablen außer "Alter" sind kategorial.

**Comment by wilson102099** [comment]
Bei Teil (b) sollte man nur für die kategoriale Variablen die Funktion testen. (hier ist aber Alter als kategorialle Variable angenommen)

**Comment by lshrnd** [comment]
Ich hab jetzt nochmal über alle Funktionen drüber geschaut, sieht alles gut aus. Be (e) weiß ich auch nicht wie man sie verbessern könnte, aber sie funktioniert ja. Wenn keiner da noch Vorschläge hat würde ich alles so lassen.

**Comment by wilson102099** [comment]
> Ich hab jetzt nochmal über alle Funktionen drüber geschaut, sieht alles gut aus. Be (e) weiß ich auch nicht wie man sie verbessern könnte, aber sie funktioniert ja. Wenn keiner da noch Vorschläge hat würde ich alles so lassen.

Ich und Amir bearbeiten gerade die Funktion. Vielleicht können wir die verbessern.

**Comment by JKuehne-TU** [comment]
Alles klar.
Dann würden wir die Auswertung zunächst mit den fertigen Funktionen (ohne Funktion (e)) durchführen. Sobald diese fertig ist können wir sie dann auch nutzen.
