### ISSUE TITLE
Problem mit Funktion (e) feedback!

### ISSUE THREAD

**Issue by wilson102099** [lshrnd/wissArbeiten_gruppe12#3]
Ich und Amir haben eine neue Funktion geschrieben und auf die Branch Funktionen + Skript hochgeladen. Die einzige möglichkeit sodass wir keine NA als Ausgabe erhalten und auch quantilbasierte Kategorisierung ist dass wir die Daten nur mit 3 Levels (niedrig, mittel, hoch) kategorisieren können. Ich warte auf eure Feedback!

**Comment by JKuehne-TU** [comment]
Ich eure Änderung der Funktion nicht auf dem Branch. Habt ihr sie comitted und gepusht?
Aber wenn eure Funktion funktioniert dann ist das gut, auch wenn es weniger Labels sind, das sollte kein Problem sein.

**Comment by wilson102099** [comment]
Ich hab die Funktion direkt in Funktionen-R-Skript1.R geschrieben.

**Comment by JKuehne-TU** [comment]
Ja, ich habe es gefunden, aber es ist nicht im Branch "Funktionen+Testskripte" sondern in main. Das ist in auch okay. Ich werde die Funktion bei der Auswertung testen und wenn sie gut funktioniert die Issue schließen, falls es aber ein Problem gibt mich hier nochmal melden.

**Comment by wilson102099** [comment]
Okay. Ich warte auf deine Feedback!

**Comment by JKuehne-TU** [comment]
Also die Funktion funktioniert sehr gut. Wir können sie anstelle der alten verwenden.
Ihr könnt im main branch gerne die alte Funktion entfernen.
Es wäre allerdings gut, wenn ihr die neue Funktion noch so kommentiert, wie die anderen Funktionen auch kommentiert sind.

**Comment by wilson102099** [comment]
Super! Ich kommentiere die neue Funktion und löschen die alte Funktion

**Comment by wilson102099** [comment]
Ich hab Teil (e) schon aktuelisiert. Danke für die Feedbacks!
