### ISSUE TITLE
Diskussion: Auswertung und Interpretation

### ISSUE THREAD

**Issue by JKuehne-TU** [lshrnd/wissArbeiten_gruppe12#4]
Wir haben die Auswertung durchgeführt und die Ergebnisse findet ihr jetzt in main in den Dateien "Auswertung.pdf" und "AuswertungNachtrag.pdf".
Diese enthalten eine Zusammenfassung der Analyseergebnisse bitte schaut euch diese an und versucht ein wenig zu interpretieren und schreibt eure Gedanken dann in diese Issue. Auch können wir hier auf die Ideen der anderen Antworten und Rückmeldungen geben.

Als Diskussionsgrundlage sind hier einige Punkte die mir aufgefallen sind:
(2.2) Es gibt nur sehr wenige Informatiker, diese Daten sind wahrscheinlich nicht repräsentativ. (Abb1)
(2.3) Obwohl die Interessensverteilungen sehr unterschiedlich sind, sind die Klassifikationen fast gleich. (Nachtrag: Abb1, Abb2; Auswertung: Abb2, Abb3) Daher sollte man bei der Interpretation der klassifizierten Daten vorsichtig sein.
(3.1) Die Lage- und Streuungsmaße nach der Aufteilung unterscheiden sich kaum. Es besteht wahrscheinlich kein Zusammenhang zwischen Mathe LK und Alter.
(3.2) Zwischen Studienfach und Interesse an Mathe besteht ein Zusammenhang der Art, dass In den Studiengänge Mathe und Statistik ein hohes Interesse an Mathe da ist und in Data Science und Informatik nur ein niedriges Interesse daran. (Abb5)
(3.3) Auch hier besteht ein hoher Zusammenhang. Data Science und Informatik Studenten haben ein höheres Interesse an Informatik als Mathe und Statistik Studenten. (Abb6)

**Comment by wilson102099** [comment]
Basierend auf den von mir erstellten Daten sind Ihre Annahmen und Analysen alle richtig interpretiert.

2.2) Informatik hat die geringste Wahrscheinlichkeit bei 10%, Mathe bei 20% und Statistik bzw. Data Science bei 35%.
2.3, 3.2 & 3.3) Die Interesse an Mathe hat eine Zusammenhang mit Statistik und Mathe. Interessen an Informatik hat eine Zusammenhang mit Data Science und Informatik. Die Studierenden, die Statistik und Mathe studieren interessieren mehr an Mathe und Data Science bzw Informatikstudenten interessieren mehr an Informatik. Wenn man diese beide Studiengänge die höchste Anteil der Daten hat, macht das Sinn wenn die Verteilung von Interesse an Mathe und -Informatik fast gleich aussieht.
3,1) Mathe-LK hat eine Zusammenhang mit die Studierenden, die an Mathe interresieren. Die Studierenden, die Mathe interessieren hat eine höhe Wahrscheinlichkeit dass sie früher Mathe-LK hatten. Also hier ist die Interpretation dass Mathe-LK  keine Zusammenhang mit Alter gibt richtig.

**Comment by wilson102099** [comment]
2.2) Statistik und Data Science haben die meisten Anteil der Daten. Inzwischen haben Informatik und Mathematik einen großen Anteilsunterschied zu Statistik und Data Science. Deswegen ist die Daten unbalanciert meiner Meinung nach.

2.3) Es gibt keine größe Unterschied zwischen die beiden Klassifikationen. Ich vermüte wegen der fast gleiche Anteil der Statistik- und Data Science Studierenden sind die beide Klassifikationen fast gleich. Studierenden, die Statistik studieren, haben mehr Interesse an Mathe und Studenten, die Data Science studieren, haben mehr Interesse an Informatik. 

2.4) Die meisten Studierende hatten früher Mathe-LK. Das macht sinn weil für diese vier Studiengänge sind Mathe sehr wichtig.

3.1) Es gibt keine signifikante Unterschied zwischen die Alter für beide Gruppen (nämlich ohne Mathe-LK und mit Mathe-LK). Ich vermüte dass Alter keine Zusammenhang mit Mathe-LK gibt.

Bei 3.2 und 3.3 stimme ich dir zu.

3.5 & 3.6) Die Studierenden, die an Mathe und Informatik interessieren, hatten am meisten Fall früher Mathe-LK. Das macht für mich sinn weil Mathe  ja essenziell für die beide Interesse ist.

**Comment by lshrnd** [comment]
Nachtrag und (3.5): Die Interessensverteilung von Mathe ist zwar linksschief, also hat der durchschnittliche Studierende eher Interesse als keine Interesse an Mathe, jedoch macht es kaum einen Unterschied, ob man Mathe-LK hatte oder nicht. An den Mosaikplots sieht man, dass die Verteilungen relativ ähnlich sind, also z.B. unabhängig davon ob man Mathe-LK hatte, die meisten ein mittleres Interesse an Mathe haben. Auch hier sind diese Verteilungen noch ähnlicher, wenn man das klassierte Modell betrachtet, was aber daran liegt, dass die Klassierung sehr grob und verzerrend ist.
Zusammenfassend haben wir also keinen Zusammenhang zwischen Mathe-LK und Interesse an Mathe feststellen können. Sollte es einen geben? Wie habt ihr das modelliert?

(3.4) Anhand der Kontingenzindizes lässt sich annehmen, dass ein Zusammenhang zwischen der Interesse an Mathe und Informatik existiert. Am Mosaikplot der unklassierten Daten lässt sich erkennen, dass es kaum Studierende gibt, die an beidem sehr stark oder am beidem sehr wenig interessiert sind. Wir interpretieren also, dass der durchschnittliche Student eines der beiden Gebiete bevorzugt oder zu keinem der beiden eine starke Meinung hat.
Betrachtet man das klassierte Modell, fällt dieser Zusammenhang etwas schwächer aus. Das ist darauf zurückzuführen, da wir nicht mehr zwischen hohem und sehr hohem Interesse unterscheiden und die Extremfälle nicht mehr betrachten können (niedrig/sehr niedrig analog).

(2.1) Das Alter der Studierenden scheint sehr symmetrisch um 25 Jahre zu liegen, der jüngste Studierende ist 4 Jahre jünger, der älteste 3 Jahre älter. Mit einer Standardabweichung von 1,58 ist nicht von einer Gleichverteilung auszugehen, dies wird davon unterstützt das auch der Modus 25 ist. Wir vermuten eine Normalverteilung.

**Comment by JKuehne-TU** [comment]
Zu (3.6) & (3.5): Auffällig ist, das die Kontingenzindizes in (3.6) höher sind als jene in (3.5). Es scheint also ein höherer Zusammenhang zwischen Mathe LK und Interesse an Informatik zu bestehen als zwischen Mathe LK und Interesse an Mathe.
Dies ist interessant, da man intuitiv das Gegenteil vermuten würde.
Eine mögliche Erklärung jedoch ist, das Interesse an Informatik ja höher ist, wenn man weniger Interesse an Mathe hat. Und auch hier somit ein "negativer" Zusammenhang besteht. Jedoch lässt sich diese Vermutung nicht durch weitere Beobachtungen bestätigen. Eventuell könnte man dazu überprüfen wie hoch die Anteile der Leute in jedem Studiengang war, die einen Mathe LK hatten. Denn dort wissen wir ja schon aus (3.3) wo ein höheres Interesse an Informatik besteht.
Ist dies nur "zufällig", oder gibt es auch hier einen vorgegebenen Zusammenhang?

Zur Klassifikation: Das die Klassifikationen so ähnlich sind kann auch damit zusammenhänge welche Quantile gewählt wurden. So ist in der hier vorgenommen Klassifikation beim 0,25- und 0,75-Quantil getrennt worden. Dadurch wird der mittlere Bereich schon als größer erwartet, was sich auch bestätigt. Vielleicht wäre es besser gewesen noch andere Quantile zur Klassifikation auszuprobieren. Und die sich ergebenden Daten miteinander zu vergleichen.

**Comment by wilson102099** [comment]
Zur Klassifikation stimme ich @JKuehne-TU zu. Weil unsere Klassifikation quantilbasiert ist, wäre es besser wenn wir andere Quantile auch berechnen sodass unsere Interpretationen genauer sind.

**Comment by wilson102099** [comment]
Basierend auf den von mir und Amir erstellten Daten sind eure Annahmen und Analysen fast alle richtig interpretiert.

2.1) Die Alter der Studenten sind Normalverteilt mit 25 als Mean und Standardabweichnung von 2.

2.2) Informatik hat die geringste Wahrscheinlichkeit bei 10%, Mathe bei 20% und Statistik bzw. Data Science bei 35%.

2.3, 3.2, 3.3 & 3.4) Die Interesse an Mathe hat eine Zusammenhang mit Statistik und Mathe. Interessen an Informatik hat eine Zusammenhang mit Data Science und Informatik. Die Studierenden, die Statistik und Mathe studieren interessieren mehr an Mathe und Data Science bzw Informatikstudenten interessieren mehr an Informatik. Wenn man diese beide Studiengänge die höchste Anteil der Daten hat, macht das Sinn wenn die Verteilung von Interesse an Mathe und -Informatik fast gleich aussieht.

3,1) Mathe-LK hat eine Zusammenhang mit die Studierenden, die an Mathe interresieren. Die Studierenden, die an Mathe hoch interessieren hat eine höhere Wahrscheinlichkeit dass sie früher Mathe-LK hatten. Also hier ist die Interpretation dass Mathe-LK keine Zusammenhang mit Alter gibt richtig. Aber irgendwie ist bei der Auswertung  die Anzahl der Studierenden, die Interesse an Informatik haben  und früher Mathe-LK hatten, größer sind obwohl die Daten für Mathe-LK lediglich von Interesse an Mathe abhängig.
